# config/routes.yaml
homepage:
  path: /home
  defaults: { _controller: 'App\Controller\DefaultController::index' }

login:
  path: /login
  defaults: { _controller: 'App\Controller\SecurityController::login' }

offer:
  path: /offer/{id}
  defaults: { _controller: 'App\Controller\OfferController::form' }

product:
  path: /product
  defaults: { _controller: 'App\Controller\ProFormController::form' }

upload:
  path: /upload
  defaults: { _controller: 'App\Controller\ProductController::product' } 

listproducts:
  path: /listproducts
  defaults: { _controller: 'App\Controller\ListProductsController::listproducts' }  

frontpage:
  path: /
  defaults: { _controller: 'App\Controller\FrontPageController::frontpage' } 
  
listuser:
  path: /listuser
  defaults: { _controller: 'App\Controller\DeleteUserController::listuser' } 

alloffers:
  path: /alloffers
  defaults: { _controller: 'App\Controller\AllOffersController::alloffers' } 

edit_product:
  path: welcome/editproduct/{id}
  defaults: { _controller: 'App\Controller\ListProductsController::edit' } 
